### ISSUE TITLE
What value of stability hyper-parameter to use?

### ISSUE THREAD

**Issue by tonyduan** [Bai-Li/STN-Code#1]
Hi,

Thanks for releasing your code.

I'm unable to find training code corresponding to the strength of the stability term 𝜸 in the paper.

Could you tell us what to use or tune over?

**Comment by Bai-Li** [comment]
Thank you for your interest. The 𝜸 we used for training is just 1. I have updated the code to make it more clear.

**Comment by tonyduan** [comment]
Thank you for the quick response! Much appreciated.
