### ISSUE TITLE
The parameters of multici.multinomialCI might be wrong

### ISSUE THREAD

**Issue by wsyOverflow** [Bai-Li/STN-Code#2]
According to the document https://cran.r-project.org/web/packages/MultinomialCI/MultinomialCI.pdf , the second parameter of multici.multinomialCI  should be significance level. However, the confidence level is feed into the function call in line 20 of the file bound.py.

**Comment by Bai-Li** [comment]
Thank you for pointing out the issue. We have fixed the bug in the code. Please note it does not change any conclusion from our paper, although figure 1 looks different now.
